import { Movie } from '../types';

export const movies: Movie[] = [
  {
    id: 1,
    title: "Inception",
    overview: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    posterPath: "https://images.pexels.com/photos/2774556/pexels-photo-2774556.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    backdropPath: "https://images.pexels.com/photos/3964426/pexels-photo-3964426.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    releaseDate: "2010-07-16",
    genres: ["Action", "Sci-Fi", "Thriller"],
    rating: 8.8,
    popularity: 9.2,
  },
  {
    id: 2,
    title: "The Shawshank Redemption",
    overview: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    posterPath: "https://images.pexels.com/photos/2873486/pexels-photo-2873486.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    backdropPath: "https://images.pexels.com/photos/1714341/pexels-photo-1714341.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    releaseDate: "1994-09-23",
    genres: ["Drama"],
    rating: 9.3,
    popularity: 8.7,
  },
  {
    id: 3,
    title: "The Godfather",
    overview: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    posterPath: "https://images.pexels.com/photos/3656855/pexels-photo-3656855.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    backdropPath: "https://images.pexels.com/photos/3945317/pexels-photo-3945317.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    releaseDate: "1972-03-24",
    genres: ["Crime", "Drama"],
    rating: 9.2,
    popularity: 8.4,
  },
  {
    id: 4,
    title: "Pulp Fiction",
    overview: "The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    posterPath: "https://images.pexels.com/photos/8112112/pexels-photo-8112112.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    backdropPath: "https://images.pexels.com/photos/7991486/pexels-photo-7991486.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    releaseDate: "1994-10-14",
    genres: ["Crime", "Drama"],
    rating: 8.9,
    popularity: 8.8,
  },
  {
    id: 5,
    title: "The Dark Knight",
    overview: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    posterPath: "https://images.pexels.com/photos/10353796/pexels-photo-10353796.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    backdropPath: "https://images.pexels.com/photos/2744744/pexels-photo-2744744.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    releaseDate: "2008-07-18",
    genres: ["Action", "Crime", "Drama", "Thriller"],
    rating: 9.0,
    popularity: 9.5,
  },
  {
    id: 6,
    title: "The Lord of the Rings: The Return of the King",
    overview: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
    posterPath: "https://images.pexels.com/photos/6447217/pexels-photo-6447217.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    backdropPath: "https://images.pexels.com/photos/8797307/pexels-photo-8797307.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    releaseDate: "2003-12-17",
    genres: ["Action", "Adventure", "Fantasy"],
    rating: 8.9,
    popularity: 8.5,
  },
  {
    id: 7,
    title: "Forrest Gump",
    overview: "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other historical events unfold through the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.",
    posterPath: "https://images.pexels.com/photos/45243/feather-ease-slightly-feel-45243.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    backdropPath: "https://images.pexels.com/photos/1122626/pexels-photo-1122626.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    releaseDate: "1994-07-06",
    genres: ["Drama", "Romance"],
    rating: 8.8,
    popularity: 8.6,
  },
  {
    id: 8,
    title: "Interstellar",
    overview: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    posterPath: "https://images.pexels.com/photos/1169754/pexels-photo-1169754.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    backdropPath: "https://images.pexels.com/photos/956999/milky-way-starry-sky-night-sky-star-956999.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    releaseDate: "2014-11-07",
    genres: ["Adventure", "Drama", "Sci-Fi"],
    rating: 8.6,
    popularity: 9.0,
  },
  {
    id: 9,
    title: "The Matrix",
    overview: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    posterPath: "https://images.pexels.com/photos/4100130/pexels-photo-4100130.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    backdropPath: "https://images.pexels.com/photos/2653362/pexels-photo-2653362.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    releaseDate: "1999-03-31",
    genres: ["Action", "Sci-Fi"],
    rating: 8.7,
    popularity: 8.9,
  },
  {
    id: 10,
    title: "Parasite",
    overview: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    posterPath: "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    backdropPath: "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    releaseDate: "2019-10-11",
    genres: ["Comedy", "Drama", "Thriller"],
    rating: 8.6,
    popularity: 8.8,
  },
  {
    id: 11,
    title: "Spirited Away",
    overview: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.",
    posterPath: "https://images.pexels.com/photos/15663257/pexels-photo-15663257/free-photo-of-silhouette-of-trees-against-sky-at-night.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    backdropPath: "https://images.pexels.com/photos/1428169/pexels-photo-1428169.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    releaseDate: "2001-07-20",
    genres: ["Animation", "Adventure", "Family", "Fantasy"],
    rating: 8.6,
    popularity: 8.2,
  },
  {
    id: 12,
    title: "The Silence of the Lambs",
    overview: "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.",
    posterPath: "https://images.pexels.com/photos/1493378/pexels-photo-1493378.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    backdropPath: "https://images.pexels.com/photos/247851/pexels-photo-247851.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    releaseDate: "1991-02-14",
    genres: ["Crime", "Drama", "Thriller"],
    rating: 8.6,
    popularity: 8.4,
  },
  {
    id: 13,
    title: "Goodfellas",
    overview: "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.",
    posterPath: "https://images.pexels.com/photos/1752806/pexels-photo-1752806.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    backdropPath: "https://images.pexels.com/photos/1687093/pexels-photo-1687093.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    releaseDate: "1990-09-12",
    genres: ["Biography", "Crime", "Drama"],
    rating: 8.7,
    popularity: 8.3,
  },
  {
    id: 14,
    title: "Life Is Beautiful",
    overview: "When an open-minded Jewish librarian and his son become victims of the Holocaust, he uses a perfect mixture of will, humor, and imagination to protect his son from the dangers around their camp.",
    posterPath: "https://images.pexels.com/photos/1486974/pexels-photo-1486974.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    backdropPath: "https://images.pexels.com/photos/1590302/pexels-photo-1590302.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    releaseDate: "1997-12-20",
    genres: ["Comedy", "Drama", "Romance", "War"],
    rating: 8.6,
    popularity: 8.1,
  },
  {
    id: 15,
    title: "Star Wars: Episode V - The Empire Strikes Back",
    overview: "After the Rebels are brutally overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training with Yoda, while his friends are pursued by Darth Vader and a bounty hunter named Boba Fett all over the galaxy.",
    posterPath: "https://images.pexels.com/photos/14913214/pexels-photo-14913214.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    backdropPath: "https://images.pexels.com/photos/1277181/pexels-photo-1277181.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    releaseDate: "1980-05-21",
    genres: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
    rating: 8.7,
    popularity: 8.7,
  },
  {
    id: 16,
    title: "Whiplash",
    overview: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
    posterPath: "https://images.pexels.com/photos/995301/pexels-photo-995301.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    backdropPath: "https://images.pexels.com/photos/2531728/pexels-photo-2531728.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    releaseDate: "2014-10-10",
    genres: ["Drama", "Music"],
    rating: 8.5,
    popularity: 8.5,
  },
];

export const getAllGenres = (): string[] => {
  const genreSet = new Set<string>();
  
  movies.forEach(movie => {
    movie.genres.forEach(genre => {
      genreSet.add(genre);
    });
  });
  
  return Array.from(genreSet).sort();
};